package es.cediant.db;
// Generated Sep 6, 2013 3:28:29 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * App generated by hbm2java
 */
public class App  implements java.io.Serializable {
    
    private static final long serialVersionUID = -7185281796990436419L;

    private Integer idApp;
    private User user;
    private String name;
    private String type;
    private String status;
    private Date instDate;
    private String logo;

    public App() {
    }

    public App(String name, String type) {
        this.name = name;
        this.type = type;
    }
    
    public App(User user, String name, String type, String status, Date instDate, String logo) {
       this.user = user;
       this.name = name;
       this.type = type;
       this.status = status;
       this.instDate = instDate;
       this.logo = logo;
    }
   
    public Integer getIdApp() {
        return this.idApp;
    }
    
    public void setIdApp(Integer idApp) {
        this.idApp = idApp;
    }
    
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }        
    
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    
    public Date getInstDate() {
        return this.instDate;
    }
    
    public void setInstDate(Date instDate) {
        this.instDate = instDate;
    }
    
    public String getLogo() {
        return this.logo;
    }
    
    public void setLogo(String logo) {
        this.logo = logo;
    }

}

