package es.cediant.db;
// Generated Jul 4, 2013 12:30:46 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.Date;

/**
 * User generated by hbm2java
 */
public class User  implements Serializable {
    
     private static final long serialVersionUID = -4620633197445499990L;

     private String userName;
     private String password;
     private String role;
     private Date lastConnection;
     private String comment;

    public User() {
    }
	
    public User(String userName, String password) {
        this.userName = userName;
        this.password = password;
        this.role = "User";
        this.lastConnection = new Date();
    }
    
    public User(String userName, String password, String role, Date lastConnection, String comment) {
       this.userName = userName;
       this.password = password;
       this.role = role;
       this.lastConnection = lastConnection;
       this.comment = comment;
    }
   
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }
    public Date getLastConnection() {
        return this.lastConnection;
    }
    
    public void setLastConnection(Date lastConnection) {
        this.lastConnection = lastConnection;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }

}


