package es.cediant.db;
// Generated Aug 29, 2013 4:45:28 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {
    
    private static final long serialVersionUID = -8145978217009799604L;

    private Integer idUser;
    private String userName;
    private String password;
    private Date created;
    private Date lastConnection;
    private String comment;
    //private Set<UsersRole> usersRoles = new HashSet<UsersRole>(0);
    private Set<UsersRole> usersRoles;
    //private Set<Process> processes = new HashSet<Process>(0);
    private Set<Process> processes;

    public User() {
    }

	
    public User(String userName, String password) {
        this.userName = userName;
        this.password = password;
    }
    public User(String userName, String password, Date created, Date lastConnection, String comment, Set<UsersRole> usersRoles, Set<Process> processes) {
       this.userName = userName;
       this.password = password;
       this.created = created;
       this.lastConnection = lastConnection;
       this.comment = comment;
       this.usersRoles = usersRoles;
       this.processes = processes;
    }
   
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Date getLastConnection() {
        return this.lastConnection;
    }
    
    public void setLastConnection(Date lastConnection) {
        this.lastConnection = lastConnection;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public Set<UsersRole> getUsersRoles() {
        /*HashSet<UsersRole> hashSet = new HashSet<UsersRole>();
        for(Iterator it = usersRoles.iterator(); it.hasNext(); ){
            hashSet.add((UsersRole) it.next());
        }*/
        //return hashSet;
        return this.usersRoles;        
    }
    
    public void setUsersRoles(Set<UsersRole> usersRoles) {
        this.usersRoles = usersRoles;
    }
    public Set<Process> getProcesses() {
        return this.processes;
    }
    
    public void setProcesses(Set<Process> processes) {
        this.processes = processes;
    }




}


